server:
  port: 8080

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://ep-twilight-waterfall-a1z22iq2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_ptHWuFqRL73K|
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom properties for Gemini API
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
